module.exports = {
  content: [],
  presets: [],
  darkMode: 'media', // or 'class'

  //Either extend or overwrite
  theme: {
    screens: {},
    colors: {},
    extend: {
      colors: {},
    },
    columns: {},
    spacing: {},
    animation: {},
    aspectRatio: {},
    backdropBlur: {},
    backdropBrightness: {},
    backdropContrast: {},
    backdropGrayscale: {},
    backdropHueRotate: {},
    backdropInvert: {},
    backdropOpacity: {},
    backdropSaturate: {},
    backdropSepia: {},
    backgroundColor: {},
    backgroundImage: {},
    backgroundOpacity: {},
    backgroundPosition: {},
    backgroundSize: {},
    blur: {},
    brightness: {},
    borderColor: {},
    borderOpacity: {},
    borderRadius: {},
    borderSpacing: {},
    borderWidth: {},
    boxShadow: {},
    boxShadowColor: {},
    caretColor: {},
    accentColor: {},
    contrast: {},
    container: {},
    content: {},
    cursor: {},
    divideColor: {},
    divideOpacity: {},
    divideWidth: {},
    dropShadow: {},
    fill: {},
    hueRotate: {},
    invert: {},
    flex: {},
    flexBasis: {},
    flexGrow: {},
    flexShrink: {},
    fontFamily: {},
    fontSize: {},
    fontWeight: {},
    gap: {},
    gradientColorStops: {},
    gridAutoColumns: {},
    gridAutoRows: {},
    gridColumn: {},
    gridColumnEnd: {},
    gridColumnStart: {},
    gridRow: {},
    gridRowStart: {},
    gridRowEnd: {},
    gridTemplateColumns: {},
    gridTemplateRows: {},
    height: {},
    inset: {},
    keyframes: {},
    letterSpacing: {},
    lineHeight: {},
    listStyleType: {},
    margin: {},
    maxHeight: {},
    maxWidth: {},
    minHeight: {},
    minWidth: {},
    objectPosition: {},
    opacity: {},
    order: {},
    padding: {},
    placeholderColor: {},
    placeholderOpacity: {},
    outlineColor: {},
    outlineOffset: {},
    outlineWidth: {},
    ringColor: {},
    ringOffsetColor: {},
    ringOffsetWidth: {},
    ringOpacity: {},
    ringWidth: {},
    rotate: {},
    saturate: {},
    scale: {},
    scrollMargin: {},
    scrollPadding: {},
    sepia: {},
    skew: {},
    space: {},
    stroke: {},
    strokeWidth: {},
    textColor: {},
    textDecorationColor: {},
    textDecorationThickness: {},
    textUnderlineOffset: {},
    textIndent: {},
    textOpacity: {},
    transformOrigin: {},
    transitionDelay: {},
    transitionDuration: {},
    transitionProperty: {},
    transitionTimingFunction: {},
    translate: {},
    width: {},
    willChange: {},
    zIndex: {},
  },

  variantOrder: [
    'first',
    'last',
    'odd',
    'even',
    'visited',
    'checked',
    'empty',
    'read-only',
    'group-hover',
    'group-focus',
    'focus-within',
    'hover',
    'focus',
    'focus-visible',
    'active',
    'disabled',
  ],
  plugins: [],
};
