import Head from 'next/head';

const Layout = ({ children }) => {
  return (
    <div className='flex min-h-screen flex-col items-center justify-center py-2'>
      <Head>
        <title>TailwindCSS - Demo</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/ss.svg' />
      </Head>

      <main className='flex w-full flex-1 flex-col items-center justify-center px-20 text-center'>
        {children}
      </main>
    </div>
  );
};

export default Layout;
